# Generated by Django 5.2.8 on 2025-12-11 07:13

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_parking_par_entry_t_647a06_idx_record_entry_time_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, help_text='车辆的车牌号码（仅支持中国大陆车牌）', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_license_plate', message='请输入有效的中国车牌号码', regex=re.compile('^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领][A-HJ-NP-Z][A-HJ-NP-Z0-9]{4,5}[A-HJ-NP-Z0-9挂学警港澳]$'))], verbose_name='车牌号'),
        ),
    ]
