# Generated by Django 5.2.8 on 2025-12-11 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0004_add_vip_vehicle_and_free_parking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理员"), ("staff", "工作人员"), ("customer", "客户")],
                        default="customer",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="手机号"),
                ),
                ("email_verified", models.BooleanField(default=False, verbose_name="邮箱已验证")),
                ("phone_verified", models.BooleanField(default=False, verbose_name="手机已验证")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "db_table": "parking_user_profile",
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("email", "邮箱验证码"),
                            ("phone", "手机验证码"),
                            ("email_activation", "邮箱激活码"),
                        ],
                        max_length=20,
                        verbose_name="验证码类型",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "注册"),
                            ("login", "登录"),
                            ("reset_password", "重置密码"),
                            ("activate", "激活账户"),
                        ],
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                ("target", models.CharField(max_length=255, verbose_name="目标（邮箱/手机号）")),
                ("code", models.CharField(max_length=10, verbose_name="验证码")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("is_used", models.BooleanField(default=False, verbose_name="已使用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
                "db_table": "parking_verification_code",
                "indexes": [
                    models.Index(
                        fields=["target", "code_type", "purpose"],
                        name="parking_ver_target_36d130_idx",
                    ),
                    models.Index(fields=["expires_at"], name="parking_ver_expires_01e582_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="手机号"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("feedback", "意见反馈"),
                            ("bug", "问题报告"),
                            ("suggestion", "功能建议"),
                            ("other", "其他"),
                        ],
                        default="feedback",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="主题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("reply", models.TextField(blank=True, null=True, verbose_name="回复")),
                (
                    "replied_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="回复时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replied_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回复人",
                    ),
                ),
            ],
            options={
                "verbose_name": "联系消息",
                "verbose_name_plural": "联系消息",
                "db_table": "parking_contact_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "message_type"], name="parking_con_status_698bf2_idx"
                    ),
                    models.Index(fields=["email"], name="parking_con_email_d5c285_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "周一"),
                            (1, "周二"),
                            (2, "周三"),
                            (3, "周四"),
                            (4, "周五"),
                            (5, "周六"),
                            (6, "周日"),
                        ],
                        verbose_name="星期",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "parking_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_schedules",
                        to="parking.parkinglot",
                        verbose_name="停车场",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="工作人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "排班表",
                "verbose_name_plural": "排班表",
                "db_table": "parking_staff_schedule",
                "indexes": [
                    models.Index(
                        fields=["parking_lot", "weekday", "is_active"],
                        name="parking_sta_parking_1a25b0_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"], name="parking_sta_user_id_702c7e_idx"
                    ),
                ],
                "unique_together": {("user", "parking_lot", "weekday")},
            },
        ),
    ]
