# Generated by Django 5.2.8 on 2025-12-11 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0006_pricingtemplate_parkinglot_areas_parkinglot_floors_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True, verbose_name="省份简称")),
                ("name", models.CharField(max_length=50, verbose_name="省份全称")),
                (
                    "is_special",
                    models.BooleanField(default=False, verbose_name="是否特殊地区（港澳台）"),
                ),
            ],
            options={
                "verbose_name": "省份",
                "verbose_name_plural": "省份",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="parkingrecord",
            name="plate_city_code",
            field=models.CharField(
                blank=True,
                help_text="从车牌号解析的地级市代号，如：E",
                max_length=1,
                verbose_name="车牌地级市代号",
            ),
        ),
        migrations.AddField(
            model_name="parkingrecord",
            name="plate_city_name",
            field=models.CharField(
                blank=True,
                help_text="从车牌号解析的地级市全称",
                max_length=50,
                verbose_name="车牌地级市名称",
            ),
        ),
        migrations.AddField(
            model_name="parkingrecord",
            name="plate_province_code",
            field=models.CharField(
                blank=True,
                help_text="从车牌号解析的省份简称，如：粤",
                max_length=2,
                verbose_name="车牌省份简称",
            ),
        ),
        migrations.AddField(
            model_name="parkingrecord",
            name="plate_province_name",
            field=models.CharField(
                blank=True,
                help_text="从车牌号解析的省份全称",
                max_length=50,
                verbose_name="车牌省份名称",
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=1, verbose_name="地级市代号")),
                ("name", models.CharField(max_length=50, verbose_name="地级市名称")),
                ("is_capital", models.BooleanField(default=False, verbose_name="是否省会")),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="parking.province",
                        verbose_name="所属省份",
                    ),
                ),
            ],
            options={
                "verbose_name": "地级市",
                "verbose_name_plural": "地级市",
                "ordering": ["province", "code"],
                "unique_together": {("province", "code")},
            },
        ),
        migrations.CreateModel(
            name="WantedVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(db_index=True, max_length=10, verbose_name="车牌号"),
                ),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=20, verbose_name="车辆类型"),
                ),
                (
                    "description",
                    models.TextField(help_text="通缉原因、车辆特征等", verbose_name="通缉描述"),
                ),
                (
                    "case_number",
                    models.CharField(blank=True, max_length=100, verbose_name="案件编号"),
                ),
                (
                    "contact_police",
                    models.CharField(blank=True, max_length=100, verbose_name="联系人/单位"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="联系电话"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "通缉中"),
                            ("caught", "已抓获"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="1-10，数字越大优先级越高", verbose_name="优先级"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="取消时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_wanted_vehicles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "通缉车辆",
                "verbose_name_plural": "通缉车辆",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleAlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("alert_time", models.DateTimeField(auto_now_add=True, verbose_name="警报时间")),
                ("is_handled", models.BooleanField(default=False, verbose_name="是否已处理")),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "notified_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="已通知用户",
                    ),
                ),
                (
                    "parking_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="parking.parkingrecord",
                        verbose_name="停车记录",
                    ),
                ),
                (
                    "wanted_vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="parking.wantedvehicle",
                        verbose_name="通缉车辆",
                    ),
                ),
            ],
            options={
                "verbose_name": "车辆警报日志",
                "verbose_name_plural": "车辆警报日志",
                "ordering": ["-alert_time"],
            },
        ),
        migrations.CreateModel(
            name="LicensePlateLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "license_plate_prefix",
                    models.CharField(
                        help_text="省份简称+地级市代号，如：粤E",
                        max_length=2,
                        unique=True,
                        verbose_name="车牌号前缀",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="可包含区县信息", verbose_name="详细描述"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plate_locations",
                        to="parking.city",
                        verbose_name="地级市",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plate_locations",
                        to="parking.province",
                        verbose_name="省份",
                    ),
                ),
            ],
            options={
                "verbose_name": "车牌号位置映射",
                "verbose_name_plural": "车牌号位置映射",
                "ordering": ["license_plate_prefix"],
                "indexes": [
                    models.Index(
                        fields=["license_plate_prefix"], name="parking_lic_license_553b6b_idx"
                    ),
                    models.Index(
                        fields=["province", "city"], name="parking_lic_provinc_964139_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="wantedvehicle",
            index=models.Index(
                fields=["license_plate", "status"], name="parking_wan_license_6ab570_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wantedvehicle",
            index=models.Index(fields=["status", "priority"], name="parking_wan_status_c24a58_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclealertlog",
            index=models.Index(
                fields=["alert_time", "is_handled"], name="parking_veh_alert_t_0ea808_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclealertlog",
            index=models.Index(
                fields=["wanted_vehicle", "is_handled"], name="parking_veh_wanted__e664ce_idx"
            ),
        ),
    ]
