# Generated by Django 5.2.8 on 2025-12-10 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间', verbose_name='更新时间')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('other', '其他')], help_text='操作的类型', max_length=20, verbose_name='操作类型')),
                ('model_name', models.CharField(help_text='被操作的模型名称', max_length=100, verbose_name='模型名称')),
                ('object_id', models.CharField(blank=True, help_text='被操作对象的ID', max_length=100, null=True, verbose_name='对象ID')),
                ('object_repr', models.CharField(blank=True, help_text='被操作对象的字符串表示', max_length=200, null=True, verbose_name='对象表示')),
                ('description', models.TextField(blank=True, help_text='操作的详细描述', verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='操作来源的IP地址', null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, help_text='浏览器或客户端信息', max_length=500, verbose_name='用户代理')),
                ('changes', models.JSONField(blank=True, help_text='记录变更前后的数据（JSON格式）', null=True, verbose_name='变更内容')),
                ('user', models.ForeignKey(blank=True, help_text='执行操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_created_idx'), models.Index(fields=['model_name', '-created_at'], name='audit_model_created_idx')],
            },
        ),
    ]
